-- =============================================================================
-- clase-ya — Phase 1: Initial schema
--
-- Conventions:
--   * All primary keys are UUID (generated by gen_random_uuid()).
--   * All timestamps are timestamptz stored in UTC.
--   * Enums are stored as varchar + CHECK constraint (values are code, not DB enum).
--   * Long text fields are `text`; short identifiers are `varchar`.
--   * Physical deletes are the exception; catalogs use `active`, accounts use `status`.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email           varchar(255) NOT NULL,
    password_hash   varchar(255) NOT NULL,
    role            varchar(20)  NOT NULL CHECK (role IN ('STUDENT', 'TEACHER', 'ADMIN')),
    status          varchar(20)  NOT NULL DEFAULT 'PENDING'
                    CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING')),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    last_login_at   timestamptz,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX idx_users_role ON users (role);
CREATE INDEX idx_users_status ON users (status);

-- -----------------------------------------------------------------------------
-- universities / academic_units / careers  (academic catalog)
-- -----------------------------------------------------------------------------
CREATE TABLE universities (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name        varchar(255) NOT NULL,
    short_name  varchar(100),
    slug        varchar(150) NOT NULL,
    city        varchar(100),
    province    varchar(100),
    country     varchar(100),
    active      boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_universities_slug UNIQUE (slug)
);

CREATE TABLE academic_units (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    university_id  uuid NOT NULL REFERENCES universities (id) ON DELETE RESTRICT,
    name           varchar(255) NOT NULL,
    code           varchar(50),
    active         boolean NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_academic_units_university_name UNIQUE (university_id, name),
    CONSTRAINT uq_academic_units_university_code UNIQUE (university_id, code)
);

CREATE TABLE careers (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    academic_unit_id  uuid NOT NULL REFERENCES academic_units (id) ON DELETE RESTRICT,
    name              varchar(255) NOT NULL,
    slug              varchar(150) NOT NULL,
    code              varchar(50),
    active            boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_careers_slug UNIQUE (slug),
    CONSTRAINT uq_careers_academic_unit_code UNIQUE (academic_unit_id, code)
);

-- -----------------------------------------------------------------------------
-- subjects / career_subjects  (subject catalog, university-independent)
-- -----------------------------------------------------------------------------
CREATE TABLE subjects (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name              varchar(255) NOT NULL,
    normalized_name   varchar(255) NOT NULL,
    slug              varchar(150) NOT NULL,
    description       text,
    active            boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_subjects_slug UNIQUE (slug),
    CONSTRAINT uq_subjects_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE career_subjects (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    career_id       uuid NOT NULL REFERENCES careers (id) ON DELETE CASCADE,
    subject_id      uuid NOT NULL REFERENCES subjects (id) ON DELETE RESTRICT,
    name_override   varchar(255),
    code            varchar(50),
    year            int CHECK (year IS NULL OR year >= 1),
    semester        int CHECK (semester IS NULL OR semester BETWEEN 1 AND 2),
    mandatory       boolean NOT NULL DEFAULT true,
    active          boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_career_subjects_career_subject UNIQUE (career_id, subject_id)
);

CREATE INDEX idx_career_subjects_subject_id ON career_subjects (subject_id);

-- -----------------------------------------------------------------------------
-- student_profiles / teacher_profiles
-- -----------------------------------------------------------------------------
CREATE TABLE student_profiles (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        uuid NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    university_id  uuid NOT NULL REFERENCES universities (id) ON DELETE RESTRICT,
    career_id      uuid NOT NULL REFERENCES careers (id) ON DELETE RESTRICT,
    current_year   int NOT NULL CHECK (current_year BETWEEN 1 AND 12),
    bio            text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_student_profiles_user UNIQUE (user_id)
);

CREATE INDEX idx_student_profiles_university_id ON student_profiles (university_id);
CREATE INDEX idx_student_profiles_career_id ON student_profiles (career_id);

CREATE TABLE teacher_profiles (
    id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id               uuid NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    bio                   text,
    verification_status   varchar(20) NOT NULL DEFAULT 'PENDING'
                          CHECK (verification_status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    latitude              numeric(9, 6) CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    longitude             numeric(9, 6) CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    address               text,
    rating_average        numeric(3, 2) NOT NULL DEFAULT 0 CHECK (rating_average BETWEEN 0 AND 5),
    rating_count          int NOT NULL DEFAULT 0 CHECK (rating_count >= 0),
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_teacher_profiles_user UNIQUE (user_id)
);

CREATE INDEX idx_teacher_profiles_verification_status ON teacher_profiles (verification_status);
CREATE INDEX idx_teacher_profiles_location ON teacher_profiles (latitude, longitude);

-- -----------------------------------------------------------------------------
-- teacher_education
-- -----------------------------------------------------------------------------
CREATE TABLE teacher_education (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id    uuid NOT NULL REFERENCES teacher_profiles (id) ON DELETE CASCADE,
    institution   varchar(255) NOT NULL,
    degree        varchar(255) NOT NULL,
    description   text,
    start_year    int NOT NULL CHECK (start_year >= 1900),
    end_year      int CHECK (end_year IS NULL OR end_year >= start_year),
    is_verified   boolean NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_teacher_education_teacher_id ON teacher_education (teacher_id);

-- -----------------------------------------------------------------------------
-- teacher_subjects  (teacher <-> career_subject many-to-many)
-- -----------------------------------------------------------------------------
CREATE TABLE teacher_subjects (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id         uuid NOT NULL REFERENCES teacher_profiles (id) ON DELETE CASCADE,
    career_subject_id  uuid NOT NULL REFERENCES career_subjects (id) ON DELETE CASCADE,
    description        text,
    years_experience   int CHECK (years_experience IS NULL OR years_experience >= 0),
    active             boolean NOT NULL DEFAULT true,
    created_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_teacher_subjects_teacher_career_subject UNIQUE (teacher_id, career_subject_id)
);

CREATE INDEX idx_teacher_subjects_career_subject_id ON teacher_subjects (career_subject_id);

-- -----------------------------------------------------------------------------
-- favorites  (student_profiles <-> teacher_profiles many-to-many)
-- -----------------------------------------------------------------------------
CREATE TABLE favorites (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id   uuid NOT NULL REFERENCES student_profiles (id) ON DELETE CASCADE,
    teacher_id   uuid NOT NULL REFERENCES teacher_profiles (id) ON DELETE CASCADE,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_favorites_student_teacher UNIQUE (student_id, teacher_id)
);

-- -----------------------------------------------------------------------------
-- conversations / conversation_participants / messages
-- -----------------------------------------------------------------------------
CREATE TABLE conversations (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE conversation_participants (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id  uuid NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    user_id          uuid NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_conversation_participants UNIQUE (conversation_id, user_id)
);

CREATE INDEX idx_conversation_participants_user_id ON conversation_participants (user_id);

CREATE TABLE messages (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id  uuid NOT NULL REFERENCES conversations (id) ON DELETE RESTRICT,
    sender_id        uuid NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    content          text NOT NULL CHECK (length(trim(content)) > 0),
    created_at       timestamptz NOT NULL DEFAULT now(),
    read_at          timestamptz,
    -- Composite FK guaranteeing, in pure SQL, that the sender is a participant.
    CONSTRAINT fk_messages_sender_is_participant
        FOREIGN KEY (conversation_id, sender_id)
        REFERENCES conversation_participants (conversation_id, user_id)
        ON DELETE RESTRICT
);

-- Covers lookups by conversation (leading column) and FK enforcement on the child side.
CREATE INDEX idx_messages_conversation_sender ON messages (conversation_id, sender_id);

-- -----------------------------------------------------------------------------
-- bookings / reviews
-- -----------------------------------------------------------------------------
CREATE TABLE bookings (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id         uuid NOT NULL REFERENCES student_profiles (id) ON DELETE RESTRICT,
    teacher_id         uuid NOT NULL REFERENCES teacher_profiles (id) ON DELETE RESTRICT,
    career_subject_id  uuid NOT NULL REFERENCES career_subjects (id) ON DELETE RESTRICT,
    scheduled_at       timestamptz NOT NULL,
    duration_minutes   int NOT NULL CHECK (duration_minutes BETWEEN 1 AND 480),
    mode               varchar(20) NOT NULL CHECK (mode IN ('ONLINE', 'IN_PERSON')),
    status             varchar(20) NOT NULL DEFAULT 'PENDING'
                       CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    calendly_event_id  varchar(255),
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_bookings_student_id ON bookings (student_id);
CREATE INDEX idx_bookings_teacher_id ON bookings (teacher_id);
CREATE INDEX idx_bookings_scheduled_at ON bookings (scheduled_at);
CREATE INDEX idx_bookings_status ON bookings (status);

CREATE TABLE reviews (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id   uuid NOT NULL REFERENCES bookings (id) ON DELETE RESTRICT,
    student_id   uuid NOT NULL REFERENCES student_profiles (id) ON DELETE RESTRICT,
    teacher_id   uuid NOT NULL REFERENCES teacher_profiles (id) ON DELETE RESTRICT,
    rating       int NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment      text,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_reviews_booking UNIQUE (booking_id)
);

CREATE INDEX idx_reviews_teacher_id ON reviews (teacher_id);
CREATE INDEX idx_reviews_student_id ON reviews (student_id);

-- -----------------------------------------------------------------------------
-- reports
-- -----------------------------------------------------------------------------
CREATE TABLE reports (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    reporter_id       uuid NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    reported_user_id  uuid NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    reason            varchar(255) NOT NULL,
    description       text,
    status            varchar(20) NOT NULL DEFAULT 'OPEN'
                      CHECK (status IN ('OPEN', 'REVIEWING', 'RESOLVED', 'REJECTED')),
    created_at        timestamptz NOT NULL DEFAULT now(),
    resolved_at       timestamptz,
    CONSTRAINT chk_reports_no_self_report CHECK (reporter_id <> reported_user_id)
);

CREATE INDEX idx_reports_reported_user_id ON reports (reported_user_id);
CREATE INDEX idx_reports_reporter_id ON reports (reporter_id);

-- -----------------------------------------------------------------------------
-- notifications
-- -----------------------------------------------------------------------------
CREATE TABLE notifications (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type        varchar(30) NOT NULL
                CHECK (type IN ('NEW_MESSAGE', 'NEW_BOOKING', 'BOOKING_UPDATE',
                                'BOOKING_REMINDER', 'NEW_REVIEW', 'REPORT_RESOLUTION', 'SYSTEM')),
    title       varchar(255) NOT NULL,
    message     text NOT NULL,
    read_at     timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_user_id ON notifications (user_id);

-- -----------------------------------------------------------------------------
-- calendly_integrations
-- -----------------------------------------------------------------------------
CREATE TABLE calendly_integrations (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id        uuid NOT NULL REFERENCES teacher_profiles (id) ON DELETE CASCADE,
    calendly_user_id  varchar(255),
    access_token      text,
    refresh_token     text,
    token_expires_at  timestamptz,
    connected_at      timestamptz,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_calendly_integrations_teacher UNIQUE (teacher_id)
);
